import type {
  BlockchainReader,
  EventDecoder,
  EventNormalizer,
  NormalizedRecord,
} from "@sera/contracts";
import type {
  BlockMetadataInput,
  BlockMetadataStore,
  CheckpointStore,
  DatabaseContext,
  PersistenceResult,
  RecordRepository,
} from "@sera/database";
import { calculateSyncRange } from "@sera/shared";
import type { Kysely } from "kysely";
import { ReorgDetector, ReorgManager } from "./reorg.js";

export type SyncPlannerFn = typeof calculateSyncRange;

/**
 * Parameters for a single end-to-end indexing iteration.
 */
export interface IndexingPipelineConfig {
  /** The block height from which indexing should start if no state exists. */
  startBlock: number;
  /** The maximum block range batch size to fetch in a single iteration. */
  batchSize: number;
  /** Contract addresses to filter logs for. */
  contractAddresses: string[];
  /** Optional event signature topic hashes to filter logs for. */
  topics?: string[];
  /** Optional unique indexer name to manage checkpoints. */
  indexerName?: string;
  /** Optional chain ID to manage checkpoints. */
  chainId?: number;
  /** The current block height indexed in the database (override). */
  currentIndexedBlock?: number | null;
}

/**
 * The outcome summary of a single indexing pipeline execution.
 */
export interface IndexingResult {
  /** The starting block height of the processed batch (inclusive). */
  fromBlock: number;
  /** The ending block height of the processed batch (inclusive). */
  toBlock: number;
  /** The latest block number retrieved from the blockchain node. */
  latestChainBlock: number;
  /** The number of logs retrieved from the blockchain node. */
  logsFetched: number;
  /** The number of successfully decoded protocol events. */
  eventsDecoded: number;
  /** The number of logs that resolved as UnknownEvent. */
  unknownEvents: number;
  /** The total number of relational records generated by normalization. */
  normalizedRecords: number;
  /** Statistics summarizing row persistence results. */
  persistenceStatistics: {
    insertedCount: number;
    updatedCount: number;
    skippedCount: number;
  };
  /** The number of remaining blocks left to sync. */
  remainingBlocks: number;
  /** True if the indexing range caught up with the latest blockchain block. */
  caughtUp: boolean;
  /** Total time elapsed in milliseconds during execution. */
  durationMs: number;
  /**
   * True if a chain reorganization was detected and recovery was performed
   * before this batch was processed.
   */
  reorgRecovered: boolean;
}

/**
 * Composes synchronization planning, reorg detection, block reading, event
 * decoding, normalization, and database storage into a single atomic iteration.
 *
 * Execution sequence:
 *   1. Read checkpoint from database.
 *   2. Run reorg check (if BlockMetadataStore is provided).
 *   3. If reorg: mark orphaned blocks non-canonical, reset checkpoint.
 *   4. Compute sync range.
 *   5. Fetch logs.
 *   6. Decode and normalize events.
 *   7. Begin transaction:
 *      a. Persist protocol records.
 *      b. Persist block metadata for every block in range.
 *      c. Update checkpoint.
 *   8. Commit.
 */
import { type MetricRecorder, NoopMetricRecorder } from "@sera/observability";

export class IndexingPipeline {
  private readonly reorgDetector?: ReorgDetector;
  private readonly reorgManager?: ReorgManager;
  private readonly recorder: MetricRecorder;

  constructor(
    private reader: BlockchainReader,
    private decoder: EventDecoder,
    private normalizer: EventNormalizer,
    private repository: RecordRepository,
    private checkpointStore?: CheckpointStore,
    private db?: Kysely<unknown>,
    private planner: SyncPlannerFn = calculateSyncRange,
    private blockMetadataStore?: BlockMetadataStore,
    private reorgConfig?: { maxRollbackDepth: number },
    recorder?: MetricRecorder,
  ) {
    this.recorder = recorder || new NoopMetricRecorder();
    if (!reader) throw new Error("BlockchainReader is required");
    if (!decoder) throw new Error("EventDecoder is required");
    if (!normalizer) throw new Error("EventNormalizer is required");
    if (!repository) throw new Error("RecordRepository is required");

    // Wire up reorg detection when the necessary stores are provided.
    if (blockMetadataStore && checkpointStore && reorgConfig) {
      this.reorgDetector = new ReorgDetector(blockMetadataStore, reader, {
        chainId: 0, // Overridden per-execute using config.chainId
        maxRollbackDepth: reorgConfig.maxRollbackDepth,
      });
      this.reorgManager = new ReorgManager(blockMetadataStore, checkpointStore);
    }
  }

  /**
   * Executes exactly one iteration of the end-to-end indexing pipeline.
   *
   * @param config Pipeline iteration configurations.
   * @returns Detailed summary statistics of the sync cycle.
   */
  public async execute(config: IndexingPipelineConfig): Promise<IndexingResult> {
    const startTime = Date.now();
    let reorgRecovered = false;

    // 1. Resolve current indexed block height from checkpoint store or config override.
    let currentIndexedBlock = config.currentIndexedBlock;
    if (
      currentIndexedBlock === undefined &&
      config.indexerName &&
      config.chainId &&
      this.checkpointStore &&
      this.db
    ) {
      currentIndexedBlock = await this.checkpointStore.getCheckpoint(
        this.db as unknown as DatabaseContext,
        config.indexerName,
        config.chainId,
      );
    }
    if (currentIndexedBlock === undefined || currentIndexedBlock === null) {
      currentIndexedBlock = null;
    }

    // 2. Reorg detection: run before planning the next sync range so that if a
    //    reorg is detected the checkpoint is rewound first and the planner
    //    picks up from the correct ancestor.
    if (
      this.blockMetadataStore &&
      this.reorgManager &&
      config.indexerName &&
      config.chainId &&
      this.db
    ) {
      const detector = new ReorgDetector(this.blockMetadataStore, this.reader, {
        chainId: config.chainId,
        maxRollbackDepth: this.reorgConfig?.maxRollbackDepth ?? 100,
      });

      const reorgResult = await detector.check(this.db as unknown as DatabaseContext);

      if (reorgResult.reorgDetected) {
        // 3. Reorg recovery: executed inside its own transaction so the
        //    checkpoint reset and metadata invalidation are atomic.
        await this.db.transaction().execute(async (trx) => {
          const trxContext = trx as unknown as DatabaseContext;
          await this.reorgManager!.markNonCanonical(
            trxContext,
            config.chainId!,
            config.indexerName!,
            reorgResult.rollbackToBlock,
          );
        });

        // Update local reference so the planner uses the rewound height.
        currentIndexedBlock = reorgResult.rollbackToBlock;
        reorgRecovered = true;
      }
    }

    // 4. Determine next block range using BlockchainReader block head + SyncPlanner.
    const latestBlockBigInt = await this.reader.getLatestBlockNumber();
    const latestChainBlock = Number(latestBlockBigInt);

    const range = this.planner({
      startBlock: config.startBlock,
      latestBlock: latestChainBlock,
      currentIndexedBlock,
      batchSize: config.batchSize,
    });

    const fromBlock = range.nextFromBlock;
    const toBlock = range.nextToBlock;

    // 5. Early exit if planner determines there is no work to do.
    if (toBlock < fromBlock) {
      return {
        fromBlock,
        toBlock,
        latestChainBlock,
        logsFetched: 0,
        eventsDecoded: 0,
        unknownEvents: 0,
        normalizedRecords: 0,
        persistenceStatistics: { insertedCount: 0, updatedCount: 0, skippedCount: 0 },
        remainingBlocks: 0,
        caughtUp: true,
        durationMs: Date.now() - startTime,
        reorgRecovered,
      };
    }

    // 6. Fetch raw blockchain logs in range.
    const logs = await this.reader.getLogs({
      fromBlock: BigInt(fromBlock),
      toBlock: BigInt(toBlock),
      address: config.contractAddresses,
      topics: config.topics,
    });

    let decodedEventsCount = 0;
    let unknownEventsCount = 0;
    const allNormalizedRecords: NormalizedRecord[] = [];

    // 7. Decode and normalize logs.
    for (const log of logs) {
      const event = this.decoder.decode(log, config.chainId);

      if (event.type === "UnknownEvent") {
        unknownEventsCount++;
      } else {
        decodedEventsCount++;
      }

      const records = this.normalizer.normalize(event);
      for (const r of records) {
        allNormalizedRecords.push(r);
      }
    }

    // 8. Persist records, block metadata, and checkpoint atomically.
    let persistResult: PersistenceResult;
    if (this.db) {
      persistResult = await this.db.transaction().execute(async (trx) => {
        const trxContext = trx as unknown as DatabaseContext;

        // 8a. Persist normalized protocol records.
        const result = await this.repository.saveRecords(trxContext, allNormalizedRecords);

        // 8b. Persist block metadata for each block in the processed range.
        //     Block hashes come from the fetched logs.  When a block has no
        //     logs we don't have header data, so we only persist metadata for
        //     blocks that appear in the log set.
        if (this.blockMetadataStore && config.chainId) {
          const blockHeaders = this.extractBlockHeaders(logs, config.chainId);
          for (const header of blockHeaders.values()) {
            await this.blockMetadataStore.saveBlock(trxContext, header);
          }
        }

        // 8c. Advance the checkpoint inside the same transaction.
        if (config.indexerName && config.chainId && this.checkpointStore) {
          await this.checkpointStore.saveCheckpoint(
            trxContext,
            config.indexerName,
            config.chainId,
            toBlock,
          );
        }

        return result;
      });
    } else {
      // Fallback for mock contexts that do not provide a real database client.
      persistResult = await this.repository.saveRecords(
        null as unknown as DatabaseContext,
        allNormalizedRecords,
      );
    }

    const durationMs = Date.now() - startTime;
    const chainIdStr = String(config.chainId || 1);

    this.recorder.incrementCounter("indexed_blocks_total", Number(toBlock - fromBlock + 1), {
      chainId: chainIdStr,
    });
    this.recorder.recordGauge("current_checkpoint", Number(toBlock), {
      indexerName: config.indexerName || "indexer",
      chainId: chainIdStr,
    });
    this.recorder.recordHistogram("block_processing_duration_ms", durationMs, {
      chainId: chainIdStr,
    });

    if (reorgRecovered) {
      this.recorder.incrementCounter("reorgs_total", 1, {
        chainId: chainIdStr,
      });
    }

    return {
      fromBlock,
      toBlock,
      latestChainBlock,
      logsFetched: logs.length,
      eventsDecoded: decodedEventsCount,
      unknownEvents: unknownEventsCount,
      normalizedRecords: allNormalizedRecords.length,
      persistenceStatistics: {
        insertedCount: persistResult.statistics.insertedCount,
        updatedCount: persistResult.statistics.updatedCount,
        skippedCount: persistResult.statistics.skippedCount,
      },
      remainingBlocks: range.remainingBlocks,
      caughtUp: range.isCaughtUp,
      durationMs,
      reorgRecovered,
    };
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  /**
   * Extracts unique block headers from a set of blockchain logs.
   * Returns a Map keyed by block_hash so each block is only persisted once.
   *
   * NOTE: We derive `parent_block_hash` as an empty sentinel here because
   * `BlockchainLog` does not carry the parent hash. Accurate parent hashes
   * are populated by the ReorgDetector when it fetches blocks from the RPC.
   * For the purposes of block_metadata persistence inside the normal indexing
   * flow, the parent hash is stored as an empty string and updated lazily
   * if ever needed for reorg tracing.
   */
  private extractBlockHeaders(
    logs: Array<{ blockNumber: bigint; blockHash: string }>,
    chainId: number,
  ): Map<string, BlockMetadataInput> {
    const headers = new Map<string, BlockMetadataInput>();

    for (const log of logs) {
      const hash = log.blockHash.toLowerCase();
      if (!headers.has(hash)) {
        headers.set(hash, {
          chainId,
          blockNumber: Number(log.blockNumber),
          blockHash: hash,
          // Parent hash is not available from log data.
          // It is populated accurately when the ReorgDetector fetches full blocks.
          parentBlockHash: "",
        });
      }
    }

    return headers;
  }
}
